nanowrimo/nanowrimo_frontend

- app/adapters/user.js
- app/routes/authenticated.js
- mirage/config.js
- mirage/factories/user.js
- mirage/scenarios/default.js
- tests/acceptance/genres-crud-test.js
- tests/acceptance/sign-in-test.js
- tests/unit/adapters/user-test.js
This is a convenience PR to load the current logged-in User as the model for the `authenticated` route. This allows any route nested under the `authenticated` route to access the current logged-in User with [`modelFor`](https://emberjs.com/api/ember/3.1/classes/Route/methods/modelFor?anchor=modelFor) as follows:
```js
// app/routes/authenticated/*.js
import Route from '@ember/routing/route';
export default Route.extend({
model() {
let user = this.modelFor('authenticated');
// Do something here using the logged-in User
}
});
```
I'm introducing this ahead of my current User profile work as it sounds like it will benefit @nanojezra's current Projects work as well.
> Load current User as model for authenticated route

- ember-cli-build.js
- package.json
- tests/integration/components/validated-input-test.js
- yarn.lock
Removing `ember-native-dom-helpers` as the functionality it provides is now available from the built-in `@ember/test-helpers`
> Enable jQuery

- app/adapters/application.js
Avoids clobbering of the Content-type header as described here: https://github.com/ember-cli/ember-fetch/issues/87
> Revert to default ember-data ajax behavior

- mirage/factories/external-link.js
- mirage/factories/favorite-author.js
- mirage/factories/favorite-book.js
- mirage/factories/fundometer.js
- mirage/factories/genre.js
- mirage/factories/project.js
- mirage/factories/user.js
- When using a faker function with default options, use `property: faker.function` (no trailing `()` or every instance will have the same value)
- When using a faker function with custom options, use `property() { return faker.function({opts}); }`
- For images, use loremflickr directly as its performance is better than `faker.image`'s use of lorempixel. End the loremflickr URL with `?random=${i}` to avoid caching duplication. Note that giving loremflickr a comma-separated list of terms operates as an OR query, so we don't typically need to use faker randomness for these.
- When needing to generate values that faker doesn't provide directly but have some aspect of randomness, leverage faker to do the random bits wherever possible.
> Clean up Mirage factories for consistency

- app/models/challenge.js
- app/models/external-link.js
- app/models/favorite-author.js
- app/models/favorite-book.js
- app/models/fundometer.js
- app/models/genre.js
- app/models/password-reset-attempt.js
- app/models/project-challenge.js
- app/models/project-genre.js
- app/models/sign-in-attempt.js
- app/models/sign-up-attempt.js
- app/models/user.js
- Destructure `DS` (results in a more module-like syntax that ember-data does plan to eventually support directly like Ember.js does)
- List attributes first, sorted alphabetically; use camelCase for all attributes
- List relationships next, sorted alphabetically
- List computed properties last (grouped alphabetically; single-line CPs then multi-line CPs)
> Make model definitions more consistent

- app/components/challenge-editor.js
- app/components/project-list-progress.js
- app/components/project-new-modal.js
- app/controllers/authenticated/users/show/projects/index.js
- app/helpers/is-equal.js
- app/models/challenge.js
- app/models/project.js
- app/routes/authenticated/users/show/projects/index.js
- app/templates/authenticated/users/show/projects/index.hbs
- app/templates/components/challenge-editor.hbs
- app/templates/components/form-for.hbs
- app/templates/components/project-listing.hbs
- app/templates/components/project-new-modal.hbs
- app/templates/components/user-edit-bio-modal.hbs
- app/templates/components/user-edit-profile-modal.hbs
- app/templates/components/validated-time-zone.hbs
- app/validations/project.js
- mirage/config.js
- mirage/factories/project.js
- mirage/scenarios/default.js
- tests/acceptance/project-announce-test.js
Clicking on the "Announce New Project" button on the Projects index page brings up a New Project modal that walks through 3 steps (Overview, Goals, Details):
A handful of stream-of-consciousness notes:
- General
- Overview (Step 1)
- Goal (Step 2)
- Details (Step 3)
I'll leave it up to you whether to merge this as-is and then work on addressing the above uncheked items or continue to work on this branch before merging.
> Announce Project

- app/controllers/authenticated/index.js
- app/routes/application.js
Moved loading of Badges and Notifications to authenticated/index route
currentUser loading is now in the after_model hook
> Refactored loading of user data

- app/templates/components/main-nav-logger-and-timer.hbs
- app/templates/components/notifications-menu.hbs
- app/templates/components/project-summary.hbs
added label to session update display button
added label to timer display button
added label to notifications button
added label to nanoMessages button
created descriptive span for project summary dropdown menu trigger that has no associated text.
the span has style "hidden" and aria-hidden="false"
> Added aria-labeling for screen readers

- app/templates/authenticated/settings/preferences.hbs
font-size 16px
target _blank (opens in new tab/window)
add a line break prior to the link
refs nano 174
> Styled link to forum email preferences

- app/components/project-stats.js
modified project-stats 'count' computed property to sum
the count of challengeSessions
refs API #291
> fixed bug where /stats was displaying bad data

- app/components/project-session-modal.js
- app/templates/components/project-session-modal.hbs
updated template to call component's "onShow" action when modal is opened
updated component to create "onShow" action that sets defaults
for date, start and end times, and count
refs API#194
> Implemented sane defaults for project-session-modal

- app/components/splash-winner.js
- app/router.js
- app/routes/authenticated/nano-winner-2019.js
refactored the determination of a "winner" to use
user.wonEventByName() method.
moved nano-winner-2019.js route to reuire authentication
display 404 if a non-winner views the route
refs API#383
> Fixed problems with the nano-winner-2019 route

- app/components/project-stats.js
- app/models/project-challenge.js
trigger the reload when the user visits the /stats route or when a project-session is saved
> Force a projectChallenge to reload its aggregates

- app/styles/theme/nw-card.scss
- app/styles/theme/nw-project.scss
- app/templates/components/project-flippy-details.hbs
added .nw-scroll-y class to nw-card
removed `overflow: scroll;` from `.nw-project-details > div` class in
nw-project
modified project-flippy-details template to use new class
refs API 398
> Limit scroll styling to initial divs in project details

- app/components/project-stats.js
modified 'sessions' computed property to to track changes in the
projectChallenge's currentCount property
refs API#442
> projectSessions are displayed in stats when they are created

- app/components/stats-days-straight.js
The last aggregate must be from today or yesterday, in order to compute
the current "Days In A Row". This requires the aggregates to be sorted
by "day" before checking the last aggregate
refs API#437
> Sort aggregates by day before checking the last aggregate

- config/environment.js
modified the environment file to allow local development to use the
staging API when running ember server with the dev-with-staging-api
environment.
From the ember source directory, run: ember s -e dev-wih-staging-api
> local development can use the staging API

- app/styles/theme/nanomessages.scss
reduced left and right padding for conversation-content
on mobile
added overflow-wrap: anywhere to .nanomessage-content
refs API#459
> break long words in chat messages

- app/templates/authenticated/index.hbs
use project.currentProjectChallenge to determine which badges to display on the
user's dashboard
refs API#508
> improved goal reference for dashboard badges

- app/controllers/authenticated/users/show/projects/show/badges.js
The badge data already exists. The computed property just needs the
badgesService to incrementRecompute
refs API#508
> Update badges without requiring an API request

- app/services/nano-menu-service.js
changed teaser text for NaNo prep to "Get ready to write a novel"
Added "Now What?" as first menu item. Set teaser text to "Editing and publishing resources"
set url to "/now-what", set image src to thought_bubble.svg
refs https://github.com/nanowrimo/api/issues/586
> Modified Writer's Resources menu

- app/styles/theme/general.scss
refs https://github.com/nanowrimo/Issues-and-Actions/issues/138
> App loading indicator is *mostly* centered vertically and horizontally

- app/components/splash-winner.js
- app/controllers/authenticated/notifications/index.js
- app/templates/authenticated/notifications/index.hbs
- app/templates/components/splash-winner.hbs
modified splash-winner template to not display goodies button if event is unknown
refs https://github.com/nanowrimo/Issues-and-Actions/issues/168
> Added extraData to splash-winner from notifications/index

- app/components/notifications-menu.js
- app/components/splash-winner.js
- app/models/project-challenge.js
- app/services/badges-service.js
- app/services/ping-service.js
modified notification-menu to simplify checking for a potential win
modified splash-winner to check a badges title only if the badge exists
modified project-challenge model to return the challenges winner badge
modified badge-service to not check for updates when loading base badge data
modified ping-service to trigger badgeService.getBaseBadgeData on init
refs https://github.com/nanowrimo/Issues-and-Actions/issues/135
> Better detection of an event win and splash display

- app/components/event-listing.js
- app/controllers/authenticated/regions/show/events/pending.js
modified pending to controller to not include rejected events in the pending list
modified event-listing to remove code that was throwing errors when a rejected event was removed from the list
refs #https://github.com/nanowrimo/Issues-and-Actions/issues/272
> Remove a rejected event from the pending event list

- app/components/version-hash.js
- app/templates/components/authenticated-footer.hbs
- app/templates/components/logged-out-footer.hbs
- app/templates/components/version-hash.hbs
This will alllow CS to ask user's what version of the software the user has loaded
in their browser.  When cross referenced with the version hash in github, it will
be easy to tell if the user's issue has to do with cached software.
> Added the github version hash to the footer

- app/components/group-listing.js
- app/styles/theme/nw-group.scss
- app/templates/components/group-listing.hbs
viewing one's own groups and another user's groups will display very similarly
refs https://github.com/nanowrimo/Issues-and-Actions/issues/257
> Modified styling
