- app/components/user-edit-links.js
- app/components/user-edit-profile-modal.js
- app/components/user-links.js
- app/controllers/authenticated/users/show.js
- app/models/external-link.js
- app/models/user.js
- app/router.js
- app/routes/authenticated/users/show.js
- app/styles/theme/panels.scss
- app/templates/authenticated/users/show.hbs
- app/templates/components/user-edit-links.hbs
- app/templates/components/user-edit-profile-modal.hbs
- app/templates/components/user-links.hbs
- app/validations/sign-up-attempt.js
- app/validations/user.js
- app/validators/uniqueness.js
- config/environment.js
- mirage/config.js
- mirage/serializers/external-link.js
- package.json
- tests/acceptance/user-profile-edit-test.js
- tests/acceptance/user-profile-test.js
- tests/integration/components/user-links-test.js
- yarn.lock
> Edit basic User profile and ExternalLinks

- app/components/bs-modal/footer.js
- app/components/user-edit-profile-modal.js
- app/controllers/authenticated/users/show.js
- app/templates/authenticated/users/show.hbs
- app/templates/components/user-edit-profile-modal.hbs
- app/templates/components/user-stats.hbs
- tests/acceptance/user-stats-test.js
> Edit User stats

- app/components/user-edit-bio-modal.js
- app/controllers/authenticated/users/show.js
- app/controllers/authenticated/users/show/index.js
- app/models/favorite-author.js
- app/models/favorite-book.js
- app/models/user.js
- app/routes/authenticated/users/show.js
- app/routes/authenticated/users/show/index.js
- app/templates/authenticated/users/show/index.hbs
- app/templates/components/form-for--textarea.hbs
- app/templates/components/form-for.hbs
- app/templates/components/user-edit-bio-modal.hbs
- mirage/config.js
- mirage/factories/favorite-author.js
- mirage/factories/favorite-book.js
- mirage/factories/user.js
- mirage/scenarios/default.js
- mirage/serializers/favorite-author.js
- mirage/serializers/favorite-book.js
- mirage/serializers/user.js
- tests/acceptance/user-bio-edit-test.js
- tests/acceptance/user-profile-test.js
- tests/acceptance/user-stats-test.js
Resolves #26 
Resolves #27 
**TODO:**
Truncated bio:
Expanded bio:
Edit bio:
Edit favorites:
> User bio and favorites

- app/components/form-for--image-upload.js
- app/components/nano-side-menu.js
- app/components/user-edit-images-modal.js
- app/components/user-stats.js
- app/controllers/authenticated/users/show.js
- app/helpers/html-safe.js
- app/models/user.js
- app/services/active-storage.js
- app/templates/authenticated/users/show.hbs
- app/templates/components/file-upload.hbs
- app/templates/components/form-for--image-upload.hbs
- app/templates/components/form-for.hbs
- app/templates/components/user-edit-images-modal.hbs
- mirage/factories/user.js
- package.json
- tests/acceptance/user-images-edit-test.js
- tests/integration/helpers/html-safe-test.js
- yarn.lock
New addons:
- ember-file-upload (for drag-and-drop behavior)
- ember-active-storage (to handle the actual uploads to Rails)
> User avatar and plate image uploads

- app/models/challenge.js
- app/models/external-link.js
- app/models/favorite-author.js
- app/models/favorite-book.js
- app/models/fundometer.js
- app/models/genre.js
- app/models/password-reset-attempt.js
- app/models/project-challenge.js
- app/models/project-genre.js
- app/models/project.js
- app/models/sign-in-attempt.js
- app/models/sign-up-attempt.js
This has been available [since ember-data 2.3](https://www.emberjs.com/blog/2016/01/12/ember-data-2-3-released.html#toc_importing-modules)
> Use module imports from ember-data

- app/adapters/application.js
- app/models/user.js
- app/serializers/genre.js
https://www.emberjs.com/blog/2016/01/12/ember-data-2-3-released.html#toc_importing-modules
> Fix other ember-data imports

- app/components/form-for--password.js
- app/controllers/authenticated/settings/account.js
- app/templates/authenticated/settings/account.hbs
- app/templates/components/form-for--password.hbs
- app/validations/user.js
validate new password
only show 'confirm password' if new password has a value
> changing password

- app/components/main-nav-logger-and-timer.js
- app/components/main-nav-timer-form.js
- app/controllers/authenticated/settings/account.js
- app/styles/theme/main-nav-logger-timer.scss
- app/templates/components/main-nav-logger-and-timer.hbs
- app/templates/components/main-nav-timer-form.hbs
added some styling
using timer duration according to the specification
> Updated timer to enable canceling timer

- app/models/project.js
edited privacy options and set default to 2 (public)
> Added extra project status options, and set default

- app/styles/theme/forgot-password.scss
> Added margin below card instructions

- app/controllers/authenticated/users/show/index.js
- app/styles/theme/profile.scss
- app/templates/authenticated/users/show/index.hbs
number of favorite the user is displaying
refs #226
> Adjust the number of lines visible in the user's bio based on the

- app/controllers/authenticated/users/show/index.js
- app/templates/authenticated/users/show/index.hbs
> Do not use truncate-multiline if user does not have  a bio

- app/components/badge-rendered.js
- app/styles/theme/cards.scss
- app/templates/components/badge-rendered.hbs
created new one-off style for the instructions
set new style to copy the form-instruction style
refs #236
> modified text and styling of instructions for self assigned badges

- app/components/project-stats.js
- app/models/challenge.js
- app/models/project-challenge.js
> Modified various methods that are dependent upon challenge.endsAt

- app/components/project-list-progress.js
> Get a project's currentProjectChallenge.goal when determining progress

- app/components/project-challenge-listing.js
- app/components/project-stats.js
- app/services/stats-params.js
- app/styles/theme/cards.scss
- app/styles/theme/projects.scss
- app/templates/components/project-challenge-listing.hbs
- app/templates/components/project-stats.hbs
created /services/stats-params.js to hold project and projectChallenge params
refs #270
> Link from projectChallenge listing to the stats for the projectChallenge

- app/styles/theme/profile.scss
- app/templates/authenticated/users/show.hbs
> Added indicator for editability of avatar on desktop

- app/styles/theme/cards.scss
- app/styles/theme/projects.scss
> modified styling for min-cards to have a min-height

- app/styles/theme/project.scss
summary and genres will now scroll when filled with data
refs #297
> Modified styling of project summary and genres

- app/styles/theme/project.scss
- app/templates/authenticated/users/show/projects/show.hbs
> Added "user can edit" visuals to project cover on project view

- app/templates/authenticated/users/show/projects/show/index.hbs
> Added flippygear thingy to project excerpt

- app/components/project-challenge-editor.js
- app/models/project.js
> Modified creation of 'startsat' for projectchallenge to use UTC

- app/components/project-stats.js
- app/models/project-challenge.js
> Compute Words Needed Today as Words Needed Today to Finish On Time

- app/models/project.js
to determine the activeProjectChallenge
refs #328
> Updated project model to use projectChallenge's 'hasEnded()' function

- app/templates/components/stats-how-i-feel.hbs
- app/templates/components/stats-where-i-write.hbs
> Empty state descriptive text is one line that breaks naturally

- app/styles/theme/cards.scss
- app/templates/components/stats-days-straight.hbs
- app/templates/components/stats-total-words.hbs
- app/templates/components/stats-words-needed-today.hbs
centered discriptive text
overrode highchart default css regarding font family
refs #312
> Adjusted styling of goal dashboard's first 3 widgets

- app/components/main-nav-session-logger.js
- app/components/project-list-progress.js
- app/models/user.js
- app/styles/theme/main-nav-logger-timer.scss
- app/templates/components/main-nav-session-logger.hbs
- app/templates/components/project-list-progress.hbs
> Better display of what is being updated in session updater

- app/components/user-edit-profile-modal.js
- app/models/user.js
- app/styles/theme/plates.scss
- app/templates/components/user-stats.hbs
changed font-weight of stat text
modified computation of wordiest projedt
refs #235
> Changed text for stat selection and display

- app/components/region-find.js
- app/templates/components/region-find.hbs
Don't display loading message if search results in no regions to display
> Speed up region search result display

- app/components/region-find.js
debounce sorting the search for a region based on a 150ms delay
> reimplemented debounce

- app/models/user.js
- app/templates/components/buddy-listing.hbs
> buddy card now uses user-avatar component

- app/components/project-new-modal.js
> Recompute unAssignedChallenges when baseChallenges changes

- app/services/nano-menu-service.js
see https://github.com/nanowrimo/api/issues/70
> Updated uservoice help desk link

- app/routes/brought-to-you-by.js
- app/templates/components/logged-out-footer.hbs
modified BTYB route to use ScrollRoute
> Added link to BTYB page in logged-out footer

- app/adapters/challenge.js
- app/components/project-new-modal.js
- app/templates/components/project-new-modal.hbs
- config/environment.js
Created challenge adapter to streamline retrieval of available events
modified template to add conditional
modified component to refresh the form, and the form nested within the form, that are within the modal
enter the commit message for your changes. Lines starting
> Fixed bug that was prohibiting reset of form data

- app/components/user-avatar.js
> Modified code to use user.laurels when determining a user's laurels

- app/controllers/authenticated/users/show/projects/show/goals.js
- app/templates/authenticated/users/show/projects/show/goals.hbs
added canAddProjectChallenge computed property to controller
display button based on canAddProjectChallenge value in template
refs api #120
> Don't show 'create goal' button if user can not create goal

- app/controllers/authenticated/index.js
- app/routes/application.js
Reverts nanowrimo/nanowrimo_frontend#483
> Revert "Refactored loading of user data"

- app/controllers/authenticated/users/show/projects/show/goals.js
refactored canAddProjectChallenge to check if currentUser.user is
the 'author' of the currently viewed project
> Resolves new bug introduced in #120

- app/components/region-find.js
- app/templates/components/nw-loading.hbs
- app/templates/components/region-find.hbs
- config/environment.js
refactored config/environments.js
> Removed console error related to google maps api

- app/components/nw-mobile-menu-logged-out.js
- app/styles/app.scss
- app/styles/theme/nw-mobile-menu-logged-out.scss
- app/templates/components/logged-out-menu.hbs
- app/templates/components/nw-mobile-menu-logged-out.hbs
created nw-mobile-menu-logged-out component
create style for new component
add style to app.scss
add mobile-menu-logged-out to logged-out-menu
refs api #164
> implemented mobile logged out menu

- app/models/user.js
attempting to alleviate an TypeError: Cannot read property 'forEach' of undefined
> Added value checking before looping an array

- app/controllers/authenticated/index.js
- app/templates/authenticated/index.hbs
modified template to add donation day banner
modified controller to check if it is donation day in America/Los_Angeles time zone
refs #193
> Created donation day flash banner

- app/controllers/authenticated/settings/delete-account.js
- app/controllers/delete-request.js
- app/router.js
- app/routes/authenticated/settings/delete-account.js
- app/routes/delete-request.js
- app/templates/authenticated/settings.hbs
- app/templates/authenticated/settings/delete-account.hbs
- app/templates/delete-request.hbs
created routes, templates, and controllers for allowing
users to delete their own account
> Account Deletion

- app/controllers/authenticated/settings/preferences.js
- app/models/user.js
- app/templates/authenticated/settings/preferences.hbs
- svg-congratulations.js
added discourseUsername to user model
added computed property to preferences to create url to forums
added conditional to preferences template to display link if url exists
refs nano 174 173
> Display link to Forums Email Preferences on settings/preferences

- yarn.lock
https://github.com/nanowrimo/nanowrimo_frontend/network/alert/yarn.lock/serialize-javascript/open
> Updated serialize-javascript to handle XSS vulnerability

- app/components/project-list-progress.js
from displaying goal information
> Fixed error in project-list-progress that was prohibiting UI

- app/components/user-stats.js
> Fixed yearsDoneCount computed property

- app/templates/components/cms-page.hbs
if an anchor request exists, scroll to it
refs API #323
> When loading a CMS page, check for an anchor request

- app/components/confirmation-modal.js
- app/styles/theme/modals.scss
- app/templates/components/confirmation-modal.hbs
- app/templates/components/project-summary.hbs
Added doublecheck functionality to confirmation-modal
added styling for doublecheck to modals.scss
modified poject-summary template to pass doubleCheck string to confirmation-modal
refs API#334
> Added "doublecheck" to project deletion confirmation

- app/components/confirmation-modal.js
- app/styles/theme/modals.scss
added 8px margin bottom to confirmation modal "question"
refs API#334
> ensure doubleCheckisChecked=false when displaying confirmation modal

- app/components/stats-days-straight.js
> Added 1 day grace period to "days straight" stat

- app/components/project-session-modal.js
- app/styles/theme/forms.scss
- app/templates/components/project-session-modal.hbs
enforce date input to stay within min/max values
created one off styling for date input
refs API#194
> fixed issues in project-session-modal

- app/components/project-session-modal.js
> If session has no start or end, make an end

- app/templates/components/splash-winner.hbs
> Hide the 3rd step of the component if the win is for Camp

- app/components/splash-winner.js
> Changed path to camp certificate to be absolute

- app/templates/components/splash-winner.hbs
on the second step of the winner splash
refs API#362
> Modified template to include but hide, the right arrow

- app/components/splash-winner.js
- app/models/user.js
- app/templates/components/splash-winner.hbs
modified user.wonEventByName() method to search all of a user's project challenges
to find a winner for an event
modified link functionality from winner splash to not require a full refresh of the web app
refs API#379
> Fixed bug in user model where detecting winning was failing

- app/components/project-session-modal.js
- app/templates/components/project-session-modal.hbs
Removed unused/uncalled code from component and template
> Enabled 'where I write' and 'how i write' in project-session-modal

- app/components/project-session-modal.js
- app/components/project-stats.js
- app/models/project-challenge.js
- app/models/project.js
refactored project-challenge model's hasEnded() method to be a computed property
refactored project-session-modal, project-stats, and project-challenge to use
newly refactored computed property
> Fixed bug where main-nav "+" trigger was visible after challenge ended

- app/components/main-nav-session-logger.js
- app/components/project-session-modal.js
- package.json
- yarn.lock
refactored components to not require lodash
updated package.json and yarn.lock
> Removed lodash library as a requirement for our codebase

- app/components/project-flippy-details.js
- app/styles/theme/nw-card.scss
- app/templates/components/project-flippy-details.hbs
modified component to not display empty divs if the project has no pinterest
or soundtrack
added .nw-break-words class to nw-card theme to force long words to break and wrap
implemented .nw-break-words for project details "title"
> Limit need for vertical scrolling in project details title

- app/components/stats-words-needed-today.js
- app/styles/theme/nw-fonts.scss
- app/templates/components/stats-words-needed-today.hbs
created .disabled style
modified component to determine if UI should be disabled
modified template to add .disabled style if UI should be disabled
> Disable text in stat if writing is not possible

- app/components/badges-card.js
- app/models/project-challenge.js
- app/templates/components/badges-card.hbs
modified project-challenge model to include eventType
modified component to compute filtered badges
refs API#434, API#435
> Filter word-count based badges based on event and goal duration

- app/components/form-for.js
- app/components/user-edit-profile-modal.js
- app/templates/components/user-edit-profile-modal.hbs
display error to user when user attempts to change name to a
name that is already in use
refs API#443
> Added error handling to user edit

- app/components/project-challenge-new-modal.js
modified component to get a list of available challenges for the user
from the API.
refs API#470
> Create New Goal form excludes assigned challenges

- app/components/stats-days-straight.js
- app/templates/components/project-stats.hbs
- app/templates/components/stats-days-straight.hbs
modified template and component to compute the
days-straight stat based on dailyAggregates
refs API#473
> Refactored Days-Straight stat

- app/components/project-stats.js
modifed project-stat to compute "when I'll finish" using
the refactored dailyAggregate data
refs API#474
> Refactored Stat to use dailyAggregate data

- app/components/badges-card.js
> Filter NaNo Winner badge by it's actual title

- app/components/project-stats.js
- app/components/stats-when-ill-finish.js
- app/templates/components/project-stats.hbs
- app/templates/components/stats-my-daily-average.hbs
- app/templates/components/stats-when-ill-finish.hbs
simplified the dailyAverage computation
refactored when I'll finish, and added copy for
the states where there is no data available
refs API#472
> Fixed issues with some stats

- app/styles/theme/sidemenu.scss
- app/templates/components/nano-side-menu.hbs
scaled down the profile image
removed *width* styles if they were wider than the menu
resized search
removed link to / that was wrapping the avatar and user name
refs API#453
> Made the mobile menu more mobile friendly

- app/styles/theme/nw-project.scss
> Removed 'height' attribute from goal-text style

- app/components/group-create-modal.js
- app/styles/theme/nw-grid.scss
- app/styles/theme/nw-panel.scss
- app/templates/authenticated/users/show/groups/index.hbs
- app/templates/authenticated/users/show/index.hbs
modified group-create-model to use the span tag
over-rode style in nw-grid
adjusted styles in nw-panel
modified groups index to put link in a div
modified users show index to wrap grid in nw-primary-content div
refs API#456
> modified participant mobile view to add spacing in sub-tabs

- app/templates/components/project-summary.hbs
> Removed "project cover edit" trigger

- app/templates/components/logged-out-menu.hbs
> Added "help desk" link to logged out menu

- app/styles/theme/nw-card.scss
- app/templates/components/cms-offer.hbs
modified css to only scroll vertically if necessary
refs API#461
> CSS scrolling changes on Offers route

- app/styles/theme/nw-panel.scss
- app/styles/theme/nw-stats.scss
moved stats specific styling to nw-stats file
added margin-bottom to all .nw-panel-intro child divs on /stats route when viewed on mobile
refs API#454
> Added spacing between elements in /stats route

- app/styles/theme/nw-project.scss
when viewed on mobile
refs API#457
> Reduced padding-top on project-progress

- app/styles/theme/nw-group.scss
- app/styles/theme/nw-sidebar.scss
> Allow text to break anywhere and not just at words

- app/components/project-stats.js
> Rounded percent complete to 2 decimal places

- app/templates/components/authenticated-footer.hbs
- app/templates/components/logged-out-footer.hbs
> Modified template to add/edit links

- app/templates/components/authenticated-footer.hbs
- app/templates/components/logged-out-footer.hbs
added a BR in authenticated footer before "Board of Directors"
replaced "National Novel Writing Month" text image with "NaNoWriMo" image
refs API#492
> Changed text of links

- app/templates/components/authenticated-footer.hbs
- app/templates/components/logged-out-footer.hbs
> Added 'Privacy Policy' links to templates

- app/templates/components/logged-out-menu.hbs
changed "Come Write In" to "Partner With Us"
refs API#494
> Changed link text

- app/components/user-stats.js
- app/models/project-challenge.js
- app/templates/components/user-stats.hbs
> Only display a single stat in Mobile

- app/controllers/authenticated/users/show/projects/show/badges.js
modified controller to to update badge data when the user switches project_challenges
refs API#508
> display correct badges

- app/styles/theme/lists.scss
- app/templates/components/group-list-item.hbs
list items have been modified to use standard HTML anchor tags to
link to region
list item css has been modified to always show home, leave, and join buttons
refs API#503
> Modified available regions list to make it usable on mobile

- app/components/form-for--input.js
- app/components/user-edit-profile-modal.js
- app/components/validation-error.js
- app/templates/components/form-for--input.hbs
- app/templates/components/user-edit-profile-modal.hbs
> Added error message to user edit modal when name taken

- app/models/project.js
> computedUser must exist before accessing the user's timezone

- app/components/user-stats.js
- app/styles/theme/nw-modals.scss
- app/templates/components/user-edit-profile-modal.hbs
- app/templates/components/user-stats.hbs
overrode css for the tabs styling on mobile
fixed bug in user-stats components that was prohibiting
UI updates when the user changes preferred display stats
refs API#455
> Attempted to make tabs in a modal "mobile friendlier"

- app/styles/theme/nw-modals.scss
Will *hopefully* make it more obvious to uses that scolling is a possibility
refs API#455
> Modified styling of mobile tabs

- app/components/continue-with.js
- app/controllers/sign-up.js
- app/templates/components/continue-with.hbs
- app/templates/sign-up.hbs
modified sign up form to add a checkbox
form submit and "continue with..." button are disabled if checkbox
is not checked.
refs API#181
> Added a Terms and Conditions checkbox to sign-up form

- .travis.yml
'useless'... quite like travis-ci at the moment :/
> Added useless carriage returns in the hopes of forcing a deploy

- app/components/project-edit-modal.js
> Show correct project title when deleting

- app/templates/components/authenticated-footer.hbs
- app/templates/components/logged-out-footer.hbs
refs https://github.com/nanowrimo/api/issues/180
> updated footer links to T&C

- app/models/user.js
refs https://github.com/nanowrimo/api/issues/567
> Improved logic for user.wonEventByName()

- app/styles/theme/general.scss
- app/styles/theme/lists.scss
- app/styles/theme/nav.scss
- app/styles/theme/nw-footer.scss
- app/styles/theme/nw-panel.scss
- app/templates/components/main-nav.hbs
Changed list style to disc from none to allow ul to have bullet points, which caused the footer, panel headings, nav bar, and a few other things to have bullet points when they shouldn't. I fixed all of those, but there may still be bullet points in places I didn't see.
> fix ul to have bullets

- app/routes/authenticated/users/show.js
> Removed 'projectSessions' as an include when requesting

- app/authenticators/nanowrimo.js
sending logout request to the API
refs https://github.com/nanowrimo/api/issues/554
> Modified Session.invalidate() fetch request to resolve after

- app/components/main-nav-session-logger.js
- app/components/project-session-modal.js
- app/templates/components/main-nav-session-logger.hbs
- app/templates/components/project-session-modal.hbs
modified templates to ensure form UI was wrapped in FORM elements
modified form handling action to stopPropagation() of the action
refs https://github.com/nanowrimo/api/issues/569
> Modified session forms to be proper HTML forms

- app/styles/theme/sidemenu.scss
Changed list style to none so there won't be anymore bullets in the nav menu in mobile.
> fix nav bullets in mobile view

- app/templates/components/event-card.hbs
Changed "URL : www..." to "Event Description" and linked the url to it.
> Change event url to event description

- app/components/project-challenge-new-modal.js
- app/templates/authenticated/users/show/projects/show/goals.hbs
- app/templates/components/project-challenge-new-modal.hbs
added proper form tags to help with input type=number
removed commented out code from component
added 'createNew' property to determine if modal is used for editing or creating new projectChallenge
set new projectChallenge start date to activeProjectChallenge.endsAt+1.day
refs https://github.com/nanowrimo/api/issues/563
> Some fixes to the new project-challenge modal

- app/templates/components/notification-rendered.hbs
- app/templates/components/splash-badge.hbs
- app/templates/components/splash-winner.hbs
added alt="" to images lacking alt attributes
refs https://github.com/nanowrimo/Issues-and-Actions/issues/1 https://hub.accessible360.com/issues/191447
> Added alt attribute to images

- app/templates/components/notifications-modal.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/2
> Changed spans to a tags

- app/styles/app.scss
- app/styles/theme/nw-buttons.scss
- app/styles/theme/nw-notifications.scss
- app/templates/components/notification-rendered.hbs
created nw-buttons scss
added nw-buttons to app.scss
modified no-notifications to make notification in buttons look like previous notifications
modified notification-rendered to use HTML button
refs https://github.com/nanowrimo/Issues-and-Actions/issues/3
> Refactored notifications in modal to be HTML buttons

- app/templates/components/project-summary.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/9
> Added alt attribute to cover image in project listing

- app/styles/theme/nw-footer.scss
- app/templates/components/logged-out-footer.hbs
modified template to add a div of class nw-footer-copyright
modified css to style nw-footer-copyright and related classes
refs https://github.com/nanowrimo/Issues-and-Actions/issues/12
> Modified styling to display footer text and graphics at 320px

- app/components/event-modal.js
- app/templates/components/event-modal.hbs
Step div is a ARIA progress
styling changes to better indicate current step
refs https://github.com/nanowrimo/Issues-and-Actions/issues/31
> new event modal step indicator is more usable for sight impaired users

- app/styles/theme/main-nav-logger-timer.scss
- app/templates/components/main-nav-timer-form.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/32
> Tab-like links in Timer/Stopwatch modal are more tab like

- app/styles/app.scss
- app/styles/theme/nw-a11y.scss
- app/templates/components/region-find.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/33
> Added screen reader only text to buttons on Find A Region

- app/components/project-session-modal.js
- app/templates/components/project-session-modal.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/37
> Stopped default propagation of form submit

- app/components/project-edit-modal.js
- app/templates/components/project-edit-modal.hbs
refs https://github.com/nanowrimo/api/issues/601
> Filtered non-currentuser created genres from genre list

- app/templates/components/project-challenge-editor.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/66
> Associated labels with form inputs

- app/templates/components/authenticated-footer.hbs
- app/templates/components/logged-out-footer.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/69
> Added codes of conduct link to both footers

- app/components/cms-user-card.js
- app/templates/components/cms-user-card.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/75
> Modified cms-user-card to hide non-visible content from screenreaders

- app/templates/authenticated/users/show/projects/show/goals.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/91
> Added label for project challenge filtering select

- app/components/nw-form-input-password.js
- app/styles/theme/general.scss
- app/templates/components/nw-form-input-password.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/72
> Ported show/hide password <a> to be a <button>

- app/templates/components/stats-progress-updates.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/95
> /stats progress update buttons are <buttons>

- app/templates/components/event-modal.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/102
> Added labels to New Event modal

- app/components/cms-page-card.js
- app/components/cms-user-card.js
- app/styles/theme/nw-card.scss
- app/templates/components/cms-page-card.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/78
> modified pep-talk cards to not use background images

- app/templates/components/badge-rendered.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/104
> Added tabindex to badges, which enabled tooltips on focus event

- app/templates/components/cms-user-card.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/77
> updated to aria-labels for cms-user-card flip buttons

- app/templates/components/nw-mobile-menu-logged-out.hbs
- app/templates/index.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/71
> Added "logo" to the alt tag for the YWP logo

- app/templates/components/main-nav-logger-and-timer.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/44
> Added screen reader only "stop timer" text to button

- app/components/region-find.js
- app/templates/components/region-find.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/129
> Converted buttongroup to tabs

- app/components/notifications-menu.js
- app/models/project-challenge.js
modified notifications-menu to observe the wonAt property of
the user's primary project's project_challenge
modified project-challenge to add winnerBadge property
refs https://github.com/nanowrimo/Issues-and-Actions/issues/135
> Display winner splash when official project_challenge wins

- app/components/notifications-menu.js
- app/models/project-challenge.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/135
> Display the winner splash when an offical challenge goal is met

- app/components/project-edit-modal.js
- app/templates/components/project-edit-modal.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/146
> Added aria attributes to tabs in projectEditModal

- app/routes/authenticated/nanowrimo-2019-winner.js
- app/routes/authenticated/nanowrimo-2020-winner.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/139
> Added missing routes for winners

- app/services/nano-menu-service.js
- app/templates/authenticated/writing-groups/show/admin.hbs
- app/templates/components/logged-out-menu.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/162
> Changed help desk links to https://nanowrimo.zendesk.com

- app/controllers/authenticated/users/show/projects/show.js
- app/templates/components/project-edit-modal.hbs
added tabindex to panels
fixed bug in show.js that opened modal with incorrect tab pre-selected
refs https://github.com/nanowrimo/Issues-and-Actions/issues/146
> Added aria-labeledby attributes to tab panels

- app/components/nw-alert.js
- app/components/nw-unconfirmed-handler.js
- app/styles/theme/nw-alert.scss
- app/templates/authenticated/dashboard.hbs
- app/templates/components/nw-alert.hbs
- app/templates/components/nw-unconfirmed-handler.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/163
> implemented 'dismisable' for nw-alerts and removed unverified HUB

- app/components/nw-unverified-handler.js
- app/styles/nw-variables.scss
- app/styles/theme/nw-alert.scss
- app/templates/application.hbs
- app/templates/components/nw-unverified-handler.hbs
Changed color of warning alert
Hide warning alert when success alert is displayed
refs https://github.com/nanowrimo/Issues-and-Actions/issues/163
> Modified Unverified Alert

- app/templates/components/nw-unverified-handler.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/163
> Added missing : to form label

- app/styles/theme/nw-avatar.scss
refs https://github.com/nanowrimo/Issues-and-Actions/issues/196
> Removed styling directive that was causing a bug in Blink engine

- app/models/project-challenge.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/265
> When determining the number of elapsed days, always round up

- app/templates/components/group-chat.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/246
> Handle group names that are not buddies or regions

- app/services/badges-service.js
- app/services/ping-service.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/273
> Use Ping to handle unbadging

- app/models/project-challenge.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/278
> Check that a badge exists before checking if it is a winner badge

- app/components/event-modal.js
- app/templates/components/event-card.hbs
modified event-card to render raw html
refs https://github.com/nanowrimo/Issues-and-Actions/issues/201
> Save innerHTML from medium editor

- app/styles/theme/nw-footer.scss
- app/templates/components/authenticated-footer.hbs
Added Community Advisory Team and dots in between
> ref nanowrimo/Issues-and-Actions#159

- app/components/notifications-menu.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/135
> Better tracking of projectChallenge.wonAt and winnerBadge detection

- app/components/project-list-progress.js
- app/styles/theme/nw-project.scss
- app/templates/components/project-list-progress.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/286
> Added link to winner page for official events to project-list-progress

- app/components/project-list-progress.js
- app/templates/components/project-list-progress.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/286
> Determine if a winner page exists before routing to the page

- app/services/notifications-service.js
- app/services/ping-service.js
ref https://github.com/nanowrimo/Issues-and-Actions/issues/273
> Reset the notifications when API says so

- app/components/project-session-modal.js
> ref nanowrimo/Issues-and-Actions#280

- app/styles/theme/nw-footer.scss
- app/templates/components/authenticated-footer.hbs
> Footer styling

- app/styles/theme/nw-footer.scss
- app/templates/components/logged-out-footer.hbs
> footer styling 

- app/routes/authenticated/now-what-2022-winner.js
> Added necessary route for Now What 2022 win verification

- app/components/project-challenge-editor.js
- app/components/project-new-modal.js
- app/templates/components/project-new-modal.hbs
> Update UI to limit editing of goals associated with challenge of type 3

- app/components/stats-my-overall-progress.js
- app/models/project-challenge.js
create project-challenge.fractionCountPerDay property
used new property to compute path to success in stat
> Path to success computed using fractions

- app/styles/theme/forms.scss
- app/templates/components/event-modal.hbs
modified template to add an id to content-editable's group wrapper
added style for the specific content editable.
refs https://github.com/nanowrimo/Issues-and-Actions/issues/201
> Embiggened the height of event description content-editable

- app/controllers/authenticated/regions/show/events.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/252
> Fix timing of requests to determine if user is ML

- app/components/event-card.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/272
> reject event from event card, and redirect to pending list

- app/components/project-new-modal.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/293
> don't determine if an event is official if no event is selected

- app/components/buddies/buddy-buttons.js
- app/templates/components/buddies/buddy-buttons.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/244
> Display spinner in button while invite approval request resolves

- app/components/heads-up-bulletin.hbs
- app/components/heads-up-bulletin.js
> Changed the bulletin text and button text

- app/components/badges-card.js
- app/models/badge.js
- app/models/project-challenge.js
modified models to use eventtype to determine winner badge
> Modified badges-card to handle change in badge title

- app/components/splash-winner.js
- app/templates/components/splash-winner.hbs
> Modified code to handle changed badge name

- app/router.js
> Re-enabled now-what-2022-winner route

- app/components/heads-up-bulletin.hbs
- app/components/heads-up-bulletin.js
- app/controllers/authenticated/dashboard.js
- app/routes/authenticated/camp-nanowrimo-april-2022-winner.js
- app/templates/authenticated/dashboard.hbs
modified heads-up-bulletin to handle 'Camp' type
modified dashboard template to use heads-up-bulletin for Camp
created winner verification route
refs https://github.com/nanowrimo/Issues-and-Actions/issues/300
> Preparing for Camp April 2022

- app/components/splash-winner.js
- app/templates/components/splash-winner.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/300
> Don't display link to winner route if route is not yet defined

- app/styles/theme/nw-nanomessages.scss
refs https://github.com/nanowrimo/Issues-and-Actions/issues/311
> Modifled padding-inline-start of lists in nanomessage-content

- app/components/event-listing-small.js
- app/templates/components/dashboard-hq.hbs
- app/templates/components/event-listing-small.hbs
modified event-listing-small to return hq slug when
isHq == true
refs https://github.com/nanowrimo/Issues-and-Actions/issues/314
> Fix lack of group in dashbaord-hq

- app/styles/theme/nw-nanomessages.scss
refs https://github.com/nanowrimo/Issues-and-Actions/issues/311
> Applied nanomessage ol and ul style to editable input

- app/styles/theme/nw-sidebar.scss
- app/templates/authenticated/regions/show.hbs
styled link to look like other links
refs https://github.com/nanowrimo/Issues-and-Actions/issues/307
> Added feedback link to Region view

- app/controllers/authenticated/regions/show/events.js
- app/routes/authenticated/users/show/buddies/index.js
- app/services/current-user.js
- app/services/ping-service.js
> Refactored out duplicate requests

- app/templates/authenticated/regions/show.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/307
> Changed link href

- app/templates/authenticated/dashboard.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/322
> Don't load associated dashboard data until currentUser.isLoaded

- app/components/region-find.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/324
> Sort a user's regions by region name

- app/styles/theme/buttons.scss
- app/templates/components/project-summary.hbs
created .nw-aux-button style to allow links to appear as buttons
> removed button within link

- app/models/user.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/336
> When requesting nanomessage groupusers, do it all in one api request

- app/components/project-challenge-new-modal.js
- app/models/project-challenge.js
recompute projectChallenge.computedChallenge when the challenge array changes
refs https://github.com/nanowrimo/Issues-and-Actions/issues/339
> Check projectChallenge.eventType when editing projectChallenge

- app/routes/application.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/350
> Modified route to not load services during an sso request

- app/routes/authenticated/users/show/projects/index.js
when loading projects, there is no need to also load the project's challenges or the
project's sessions
refs https://github.com/nanowrimo/Issues-and-Actions/issues/353
> projects route does not need project-sessions or challenges

- app/templates/components/dashboard-nano-store.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/361
> modified display of image based on item data

- app/templates/components/event-listing-small.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/371
> Removed unnecessary group slug from event-listing-small

- app/components/event-card.js
- app/routes/authenticated/regions/show/events/show.js
- app/templates/authenticated/regions/show/events/show.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/391
> Pass group data to event card to determine if user can admin events

- app/components/project-list-progress.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/393
> Improved computation of Goal Icon

- app/routes/authenticated/regions/show/events/upcoming.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/392
> Include Event GroupUsers in Group Events query

- app/styles/theme/general.scss
- app/templates/index.hbs
Removed "behind-the-scenes" component from index.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/401
> Removed Tent graphic from CSS

- app/components/project-session-modal.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/412
> /stats progress update form times default to the last hour

- app/templates/components/main-nav-session-logger.hbs
refactored main nav form to exclude project switching buttons
refs https://github.com/nanowrimo/Issues-and-Actions/issues/411
> Pressing enter in word-count form does not switch projects

- app/components/project-list-progress.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/273
> Winner Link in project-list-progress depends upon goal being met

- app/controllers/authenticated/dashboard.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/409
> Enabled "how to win" HUB

- .gitignore
- deploy-production
- deploy-staging
Scripts will fail if there are uncommited or modified files
added a personal directory to .gitignore
> Updated deploy scripts

- app/controllers/authenticated/dashboard.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/409
> No longer display How To Win HUB

- app/components/project-challenge-new-modal.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/422
> Revert to default values when deselecting association

- app/components/project-challenge-new-modal.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/422
> Default to empty values.

- app/components/project-challenge-new-modal.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/422
> commented out references to startTime

- app/templates/components/logged-out-footer.hbs
ref https://github.com/nanowrimo/Issues-and-Actions/issues/426
> Replaced routing LinkTo with an link to anchor tag

- app/styles/theme/nw-project.scss
ref https://github.com/nanowrimo/Issues-and-Actions/issues/286
> Added left margin to winner-route in project listing

- app/templates/components/project-list-progress.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/286
> LinkTo winner route is titled 'Winner'

- app/components/main-nav-timer-form.js
- app/styles/theme/main-nav-logger-timer.scss
- app/templates/components/main-nav-timer-form.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/84
> added aria-labeledby tags to tabs

- app/components/buddies/buddy-buttons.js
- app/components/buddies/buddy-list.js
- app/templates/components/buddies/buddy-list.hbs
- app/templates/components/buddies/buddy-listing.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/244
> show buddies when user handles all pending buddy requests

- app/styles/theme/logged-out.scss
- app/templates/components/logged-out-menu.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/137
> Modified logged out moble styling

- app/routes/authenticated/settings/account.js
- app/routes/authenticated/settings/delete-account.js
- app/routes/authenticated/settings/preferences.js
- app/routes/authenticated/settings/privacy.js
modified to settings routes to return an promise from the model() method refs https://github.com/nanowrimo/Issues-and-Actions/issues/438
> Remove loading graphic after app is loaded

- app/components/dashboard-writing-groups.js
- app/models/user.js
- app/styles/theme/new/nw-user-card.scss
- app/templates/components/dashboard-writing-groups.hbs
cleanup some logic and midified styling
refs https://github.com/nanowrimo/Issues-and-Actions/issues/444
> Added "see all" to dashboard writing groups

- app/components/progress-update.js
- app/components/project-session-modal.js
- app/components/project-stats.js
- app/components/stats-progress-updates.js
- app/templates/components/project-stats.hbs
- app/templates/components/stats-progress-updates.hbs
Added deleteFromLocalSessions action to stats-progress-updates Added addToLocalSessions action to stats-progress-updates
passed deleteFromLocalSessions to progress-update component passed addToLocalSessions action to project-session-modal component
refs https://github.com/nanowrimo/Issues-and-Actions/issues/452
> Keep session data local to stats-progress-updates

- app/components/nanomessage-form.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/461
> Show messaging form when ML views nanomessages for their region

- app/templates/components/event-card.hbs
- app/templates/components/event-modal.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/459
> Modified text and styling

- app/templates/components/project-summary-ux.hbs
> Added 'featured' flippy doodle to dashboard project summary

- app/styles/app.scss
> re-included nw-badges for styling

- app/models/project-challenge.js
- app/templates/components/project-summary-ux.hbs
> Added Percent Complete to dashboard stats

- app/components/badges-card.js
- app/components/badges-ux.js
> Filter out Now What? badge

- app/components/project-summary-ux.js
- app/templates/components/project-summary-ux.hbs
> Rerender the highchart on dashboard when the project or goal changes

- app/components/project-summary-ux.js
> Check for badges when projectChallenges changes

- app/components/stats-my-overall-progress-ux.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/476
> Display date label for the first and last day of the challenge

- app/components/stats-my-overall-progress.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/476
> display start and end date in chart

- app/services/nano-menu-service.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/478
> Updated navigation

- app/services/nano-menu-service.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/478
> Fixed broken link for Local Partners

- app/router.js
- app/routes/authenticated/camp-nanowrimo-july-2023-winner.js
modified router.js to include camp july 2023
added route for new camp event
refs https://github.com/nanowrimo/Issues-and-Actions/issues/480
> camp event created

- app/components/heads-up-bulletin.js
- app/templates/components/project-new-simple-modal-buttons.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/480
> Modified text

- app/templates/components/event-listing.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/445
> Added URL to event listing (if url exists)

- app/components/event-modal.js
> Don't save user as admin when submitting an edit

- app/components/event-modal.js
> Resolved issue with duration not being submitted on edit

- app/controllers/authenticated/settings/account.js
- app/services/current-user.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/489
> store current user email address in currentUser service on load

- app/components/event-card.js
- app/templates/components/event-card.hbs
> Update event time and duration display after editing

- app/components/event-card.js
> Event creators can not edit events

- app/models/group.js
- app/templates/components/event-card.hbs
- app/templates/components/event-listing.hbs
check for edited state when displaying regional events
> Added Edited information to group model

- app/models/user.js
- app/templates/authenticated/settings/preferences.hbs
- app/templates/components/event-card.hbs
- app/templates/components/event-listing.hbs
> Added UI for Event preferences, edited event styling

- app/templates/authenticated/settings/preferences.hbs
> Improved text for event notification preference

- app/templates/authenticated/settings/preferences.hbs
> modifed preference text

- app/components/event-modal.js
- app/templates/components/event-modal.hbs
> refactored setting of duration hours and minutes

- app/router.js
- app/routes/authenticated/nanowrimo-2023-winner.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/498
> Added routing for 2023 NaNo winner page

- app/components/group-listing.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/499
> Show the last message in groups and regions listing

- app/components/event-modal.js
ref https://github.com/nanowrimo/Issues-and-Actions/issues/202
> Fixed bug with durationHours Changes

- app/components/heads-up-bulletin.js
- app/components/project-new-simple-modal-buttons.js
- app/components/project-new-simple-modal.js
- app/templates/components/project-new-simple-modal-buttons.hbs
- app/templates/components/project-new-simple-modal.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/498
> Test changes

- app/routes/authenticated/users/show/groups/index.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/499
> reload user's regions and writing groups when accessing /groups route

- app/components/group-users-list.js
- app/templates/components/group-users-list.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/52
> Updated language regarding limit to group member number

- app/templates/sign-up.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/504
> Reordered form elements in sign up form

- app/templates/components/region-find.hbs
> Removed Find A Region Map, realigned region list

- app/styles/theme/nw-grid.scss
- app/templates/authenticated/regions/find.hbs
- app/templates/components/region-find.hbs
> Find Region as a 2 column layout

- app/templates/components/region-find.hbs
> Removed "Find By Location" as a find a region option

- app/styles/theme/nw-grid.scss
> Find A Region cards stack when screen width shrinks

- app/router.js
- app/routes/what-is-nanowrimo.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/506
> Redirect 'what-is-nanowrimo' to /

- app/components/event-modal.js
- app/templates/components/region-find.hbs
> Disable stopgapfix for location autocomplete

- app/styles/theme/forms.scss
- app/templates/components/cms-offer.hbs
modified cms-offer.hbs template to be valid html and to add a class to a form modified forms.scss to add styling for the new forms in the template
refs https://github.com/nanowrimo/Issues-and-Actions/issues/511
> Claim Offer button is now visible for tier 2 sponsors

- app/styles/theme/nw-sidebar.scss
- app/templates/authenticated/regions/show.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/520
> Added disclaimer and styling

- app/components/event-modal.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/524
> unselecting "online" when editing a regional event removes the url

- app/templates/authenticated/regions/show.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/520
> updated disclaimer text

- app/controllers/authenticated/settings/preferences.js
- ember-cli-build.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/489
> Added user's email to model when editing preferences

- app/components/project-summary.js
- app/templates/components/project-summary.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/533
> Do not show Create New Goal button on buddy's profile

- app/router.js
refs https://github.com/nanowrimo/Issues-and-Actions/issues/534
> Removed route for /press

- app/templates/components/event-card.hbs
- app/templates/components/event-modal.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/459
> Updated text for Event seating options

- app/templates/authenticated/winners-circle-2022.hbs
- app/templates/authenticated/winners-circle.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/507
> Changed email address references

- app/routes/authenticated/year-in-review/index.js
- app/templates/authenticated/year-in-review/show.hbs
modified text in template
modified index route to redirect to /year-in-review/CURRENT_YEAR
> Updated Year In Review

- app/controllers/authenticated/year-in-review/show.js
- app/routes/authenticated/year-in-review/show.js
- app/templates/authenticated/year-in-review/show.hbs
modified controller to reference other years
modified route to pass params to controller
modified template to display links to other years
> Updated year-in-review

- app/controllers/authenticated/year-in-review/show.js
> Better handling of changes to the user model

- app/controllers/authenticated/year-in-review/show.js
> Fixed bug when reading lenght or 'otherYears'

- app/templates/components/authenticated-footer.hbs
- app/templates/components/logged-out-footer.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/551
> Removed links to community advisory team

- app/controllers/authenticated/year-in-review/show.js
> Sort list of other years in reverse cron order

- app/controllers/authenticated/year-in-review/show.js
- app/templates/authenticated/year-in-review/show.hbs
> Modified text for Previous years in review

- app/controllers/authenticated/year-in-review/show.js
- app/templates/authenticated/year-in-review/show.hbs
> Modified styling and text

- app/controllers/sign-up.js
- app/templates/sign-up.hbs
ref https://github.com/nanowrimo/Issues-and-Actions/issues/556
> Added hCaptch to sign up

- app/controllers/forgot-password.js
- app/templates/forgot-password.hbs
refs https://github.com/nanowrimo/Issues-and-Actions/issues/556
> Added h-reCaptcha to password reset form

- app/templates/components/logged-out-footer.hbs
- app/templates/components/logged-out-menu.hbs
- app/templates/components/nw-mobile-menu-logged-out.hbs
- app/templates/index.hbs
- app/templates/sign-in.hbs
- app/templates/sign-up.hbs
routing to captcha containing routes are now links which forces the browser to always load the captcha creation code
refs https://github.com/nanowrimo/Issues-and-Actions/issues/556
> Refactored routing to be html links

- app/components/micro-nav.js
- app/services/current-user.js
- app/services/nano-menu-service.js
- app/templates/components/micro-nav.hbs
fixed bug in menus that was always hiding forums and regions
refs https://github.com/nanowrimo/Issues-and-Actions/issues/563
> Hide search if user is not over 18
